application:
  properties:
    host: 10.26.128.7
spring:
  cloud:
    consul:
      host: ${application.properties.host}
      port: 8500
      discovery:
        port: ${server.port}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
  zipkin:
    base-url: ${application.properties.host}:9411/