spring:
  cloud:
    consul:
      host: 10.27.1.4
      port: 8500
      discovery:
        port: ${server.port}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}