spring:
  cloud:
    consul:
      host: http://10.27.1.17
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
  zipkin:
    base-url: http://10.27.1.17:9411/