server:
  port: 8282
spring:
  datasource:
    url: jdbc:h2:mem:tp4DB
    username: user
    password: pswd
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2